### ISSUE TITLE
karrot-0005: 샘플코드 작성

### ISSUE THREAD

**Issue by tae0y** [spring-toy-project-2023/karrot-market#9]
- jpa 샘플코드작성
- junit 저장/조회 테스트작성

**Comment by hello-yoochul** [comment]
## 의논해볼것
- BaseController
  - 지금 필요하지 않으니, 넣지 않는게 좋을 것 같다.
  -  "[I avoid Base classes unless absolutely necessary.](https://stackoverflow.com/questions/28919647/basecontroller-uses-for-what-in-mvc)"
  - 개인적으로 궁금: 컨트롤러 공통 기능이 무엇이 있을까? 
- TEST 코드에 print? + 개인적으로 테스트코드 제목들은 영어로 하는게 좋을듯
- [@SpringBootTest 와 @DataJpaTest 중에 어떤걸 사용해야 하지?](https://stackoverflow.com/questions/59097035/springboottest-vs-webmvctest-datajpatest-service-unit-tests-what-is-the-b)
- 우리 회사코드에는 VO, DTO 라는 이름이 아예 없음. 꼭 사용해야만 하는가?
  - [Difference Between POJO, JavaBeans, DTO and VO](https://www.baeldung.com/java-pojo-javabeans-dto-vo)
- [@Data = @ToString , @EqualsAndHashCode , @Getter / @Setter and @RequiredArgsConstructor](https://projectlombok.org/features/Data)
- 불필요한 종속성 추가
  - MySQL 대신 Postgresql 사용
- Import * 사용하지 않기 
  - [Why is using a wild card with a Java import statement bad?](https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad)
